frontend:
  root:
    url: http://localhost:4200/
    domain: https://booking.dev-ver2.meu-solutions.com
server:
  port: 5051
  error:
    include-stacktrace: never
  JWT:
    KEY: eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4c
    EXP: 86400000
logging:
  level:
    org:
      hibernate:
        SQL: debug

spring:
  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://27.74.255.96:5433/meu_booking_engine_v2
    password: NSzo4uDp
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_updates: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  servlet:
    session:
      cookie:
        http-only: true
        max-age: 86400000s #3hours
        name: WD_SESSION
    encoding:
      charset: UTF-8
      force: true
  session:
    store-type: redis
    redis:
      cleanup-cron: 0 0 * * * *